name: math_lab
description: Dart math lab
version: 1.0.0
homepage: https://github.com/pyzworld/math_lab

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  # https://github.com/a14n/dart-decimal
  rational: ">=2.0.0 <5.0.0"
  # https://github.com/a14n/dart-decimal
  decimal: ">=2.0.0 <5.0.0"